[[usage]]
== 快速开始

为了帮助用户快速使用云服务器（CVM）API，这里给出一个使用示例，它能够引导您使用API服务完整的创建并销毁一个实例。


=== 创建一个新的实例


在创建实例前，我们首先需要确定其配置，因为它决定了用户所创建实例的性能。

___________________________________________________________________________________________________________________________________________________________________________
平台支持的有关配置，用户可以参考https://cloud.tencent.com/doc/product/213/497#3.-.E6.9C.BA.E5.9E.8B[CVM实例机型] 和 https://cloud.tencent.com/doc/product/213/2177[CVM实例配置]。
___________________________________________________________________________________________________________________________________________________________________________

假设我们想创建一个新的广州二区的 Windows 2008 操作系统的实例，所需要需要的最小请求参数是：

[cols=",,",options="header",]
|=======================================================================
|参数名称 |描述 |取值
|Zone |https://cloud.tencent.com/doc/api/229/1286[可用区]ID |ap-guangzhou-2
|ImageId |镜像ID |img-lkxqa4kj
|InternetAccessible.InternetMaxBandwidthOut |公网带宽值 |1
|=======================================================================

未在参数中指明的则使用默认值；

* 默认的标准机型：S1.SMALL1
* 密码将会自动生成，并通过站内信的形式下发。
* 这里我们指定的镜像为 Windows 2008，其它标准操作系统的 ImageId 可见https://cloud.tencent.com/doc/api/229/1272[镜像列表]

也可以修改这些默认值以便修改根据您的需要来创建实例，这一点可以详细参考 https://cloud.tencent.com/doc/api/229/1350[RunInstances]，它详尽的列出了每个可能的参数。

除了两个请求之外，还需要增加公共请求参数，最终得到的请求形式如下：

[source,bash]
----
GET https://cvm.api.qcloud.com/v2/index.php?
&Action=RunInstances
&Version=2017-03-20
&ImageId=img-lkxqa4kj
&Zone=ap-guangzhou-2
&Region=ap-guangzhou
&Nonce=7000
&SecretId=AKIDxxxxugSKIP
&Signature=5umi9gUWpTTyk18V2g%2FYi56hqls%3D
----

上述请求的返回结果如下

[source,json]
----
{
    "Response": {
        "InstanceSet": [
           "ins-a19qoqqk"
        ],
        "RequestId": "22471ac8-24a1-4653-af32-e375fb64ab58"
    }
}
----

由结果可知，新创建的实例的ID是 `ins-a19qoqqk`。这个ID唯一标识了这个实例。后续将实例进行退还操作或是调整配置都需要通过它来指定对象。


=== 查询实例


当拥有了一个实例ID时，我们可以使用 `DescribeInstances` 查询这个实例的相关信息。

[source,bash]
----
GET https://cvm.api.qcloud.com/v2/index.php?
&Action=DescribeInstances
&Version=2017-03-20
&InstanceIds.0=ins-a19qoqqk
&Region=ap-guangzhou
&Nonce=7000
&SecretId=AKIDxxxxugSKIP
&Signature=5umi9gUWpTTyk18V2g%2FYi56hqls%3D
----

[source,json]
----
{
    "Response": {
        "TotalCount": 1,
        "InstanceSet": [
            {
                "Placement": {
                    "Zone": "ap-guangzhou-2",
                    "HostId": null,
                    "ProjectId": 0
                },
                "InstanceId": "ins-a19qoqqk",
                "InstanceType": "S1.SMALL1",
                "CPU": 1,
                "Memory": 1,
                "InstanceName": "未命名",
                "InstanceChargeType": "POSTPAID_BY_HOUR",
                "DataDisks": [],
                "PrivateIpAddresses": [
                    "172.16.0.140"
                ],
                "PublicIpAddresses": [
                    "139.199.232.98"
                ],
                "InternetAccessible": {
                    "InternetMaxBandwidthOut": 0,
                    "InternetChargeType": "BANDWIDTH_POSTPAID_BY_HOUR"
                },
                "VirtualPrivateCloud": {
                    "VpcId": "vpc-8xug6adl",
                    "SubnetId": "subnet-4c7w5wii",
                    "AsVpcGateway": false
                },
                "ImageId": "img-lkxqa4kj",
                "RenewFlag": null,
                "CreatedTime": "2017-05-25T08:50:23Z",
                "ExpiredTime": null,
            }
        ],
        "RequestId": "22471ac8-24a1-4653-af32-e375fb64ab58"
    }
}
----


=== 登录 Windows 实例

从`DescirbeInstances`的返回包（上述）中找到 `Response.InstanceSet.0.PublicIpAddresses` 字段，该字段为您实例的公网IP。在Windows 中搜索”远程桌面"功能并运行，输入IP，账户名以及密码即可登录实例。

* Windows 默认账户名为 Administrator。
* 密码是您创建实例时指定的值，没有指定的话将会通过站内信下发给您。


=== 退还这个实例。


由于按量计费类型的实例会实时计费，不需要的时候我们可以主动退还它。 具体的接口请求参数见下表：

[cols=",,,",options="header",]
|==============================
|参数名称 |是否必选 |类型 |描述
|InstanceId |是 |String |实例ID
|==============================

结合公共请求参数和接口请求参数，最终得到的请求形式如下：

[source,bash]
----
https://cvm.api.qcloud.com/v2/index.php?
&Action=TerminateInstances
&Version=2017-03-20
&InstanceIds.0=ins-a19qoqqk
&Region=ap-guangzhou
&Timestamp=1465750149
&Nonce=46364
&SecretId=AKIDxxxxugEY
&Signature=5umi9gUWpTTyk18V2g%2FYi56hqls%3D
----

[source,json]
----
{
    "Response": {
        "RequestId": "22471ac8-24a1-4653-af32-e375fb64ab58"
    }
}
----

如果没有异常，则证明退还成功。